# This file was generated by db-introspector-gadget
# https://github.com/sesgoe/db-introspector-gadget

# This file requires Python >= 3.10
# If this is in error, please check the --minimum-python-version (-p) argument

import datetime
from typing import Any, TypedDict


class AuthGroup(TypedDict):
    id: int
    name: str


class AuthGroupPermissions(TypedDict):
    group_id: int
    id: int
    permission_id: int


class AuthPermission(TypedDict):
    codename: str
    content_type_id: int
    id: int
    name: str


class AuthUser(TypedDict):
    date_joined: datetime.datetime
    email: str
    first_name: str
    id: int
    is_active: bool
    is_staff: bool
    is_superuser: bool
    last_login: datetime.datetime | None
    last_name: str
    password: str
    username: str


class AuthUserGroups(TypedDict):
    group_id: int
    id: int
    user_id: int


class AuthUserUserPermissions(TypedDict):
    id: int
    permission_id: int
    user_id: int


class CorsheadersCorsmodel(TypedDict):
    cors: str
    id: int


class DjangoAdminLog(TypedDict):
    action_flag: int
    action_time: datetime.datetime
    change_message: str
    content_type_id: int | None
    id: int
    object_id: str | None
    object_repr: str
    user_id: int


class DjangoContentType(TypedDict):
    app_label: str
    id: int
    model: str


class DjangoMigrations(TypedDict):
    app: str
    applied: datetime.datetime
    id: int
    name: str


class DjangoSession(TypedDict):
    expire_date: datetime.datetime
    session_data: str
    session_key: str


class DjangoSite(TypedDict):
    domain: str
    id: int
    name: str


class EnsemblAssembly(TypedDict):
    assembly_full_name: str
    assembly_id: str
    assembly_ucsc: str | None
    blat_mapping: int | None
    common_name: str | None
    division: str | None
    ensembl_url: str | None
    example_chromosome: str | None
    example_end: int | None
    example_start: int | None
    gca_accession: str | None
    selected_genome: bool
    subdomain: str
    taxid: int


class EnsemblCompara(TypedDict):
    ensembl_transcript_id: str
    homology_id: int
    id: int
    urs_taxid: str


class EnsemblCoordinateSystems(TypedDict):
    assembly_id: str
    chromosome: str
    coordinate_system: str
    id: int
    is_reference: bool
    karyotype_rank: int | None


class EnsemblImportTracking(TypedDict):
    database_name: str
    id: int
    task_name: str
    was_imported: bool | None


class EnsemblPseudogeneExons(TypedDict):
    exon_start: int
    exon_stop: int
    id: int
    region_id: int | None


class EnsemblPseudogeneRegions(TypedDict):
    assembly_id: str | None
    chromosome: str
    exon_count: int
    gene: str
    id: int
    region_name: str
    region_start: int
    region_stop: int
    strand: int


class GoTermAnnotations(TypedDict):
    assigned_by: str | None
    evidence_code: str
    extensions: str | None
    go_term_annotation_id: int
    ontology_term_id: str
    qualifier: str
    rna_id: str


class GoTermPublicationMap(TypedDict):
    go_term_annotation_id: int
    go_term_publication_mapping_id: int
    reference_id: int


class InsdcSoTermMapping(TypedDict):
    rna_type: str
    so_term_id: str


class LitscanStatistics(TypedDict):
    articles: int | None
    expert_db: int | None
    id: int
    ids_in_use: int | None
    searched_ids: int | None
    urs: int | None


class LoadCompara(TypedDict):
    ensembl_transcript: str
    homology_group: str


class LoadEnsemblPseudogenes(TypedDict):
    assembly_id: str
    chromosome: str
    exon_count: int
    exon_start: int
    exon_stop: int
    gene: str
    region_name: str
    strand: int


class LoadGenomeMappingAttempted(TypedDict):
    assembly_id: str
    last_run: datetime.datetime
    urs_taxid: str


class LoadKaryotypes(TypedDict):
    assembly_id: str
    karyotype: str | None


class LoadModelAssignments(TypedDict):
    model_name: str
    so_term_id: str


class LoadQaRfamAttempted(TypedDict):
    last_run: datetime.datetime | None
    model_source: str
    source_version: str
    urs: str


class LoadRefPubmed(TypedDict):
    authors: str | None
    doi: str | None
    location: str | None
    ref_pubmed_id: int | None
    title: str | None


class LoadRfamGoTerms(TypedDict):
    ontology_term_id: str
    rfam_model_id: str


class LoadRncCoordinates(TypedDict):
    accession: str | None
    assembly_id: str | None
    chromosome: str | None
    local_end: int | None
    local_start: int | None
    strand: int | None


class LoadRncSecondaryStructure(TypedDict):
    md5: str | None
    rnc_accession_id: str | None
    secondary_structure: str | None


class LoadRncTextMining(TypedDict):
    authors: str | None
    doi: str | None
    location: str | None
    matching_word: str | None
    md5: str | None
    pattern: str | None
    pattern_group: str | None
    pmid: str | None
    sentence: str | None
    title: str | None


class LoadSecondaryLayout(TypedDict):
    basepair_count: int
    model: str
    model_coverage: float | None
    model_start: int | None
    model_stop: int | None
    overlap_count: int
    secondary_structure: str
    sequence_coverage: float | None
    sequence_start: int | None
    sequence_stop: int | None
    urs: str


class LoadTravelerAttempted(TypedDict):
    r2dt_version: str | None
    urs: str


class OntologyTerms(TypedDict):
    definition: str | None
    name: str | None
    ontology: str | None
    ontology_term_id: str


class PipelineTrackingGenomeMapping(TypedDict):
    assembly_id: str
    id: int
    last_run: datetime.datetime
    urs_taxid: str


class PipelineTrackingQaScan(TypedDict):
    id: int
    last_run: datetime.datetime
    model_source: str
    source_version: str
    urs: str


class PipelineTrackingTraveler(TypedDict):
    id: int
    last_run: datetime.datetime
    r2dt_version: str | None
    urs: str


class ProteinInfo(TypedDict):
    description: str | None
    label: str | None
    protein_accession: str
    synonyms: Any | None


class Publications(TypedDict):
    database: str
    id: int
    results: int
    total_ids: int


class QaStatus(TypedDict):
    from_repetitive_region: bool
    has_issue: bool
    incomplete_sequence: bool
    messages: str
    missing_rfam_match: bool
    possible_contamination: bool
    possible_orf: bool
    rna_id: str
    taxid: int
    upi: str


class ReleaseStats(TypedDict):
    active_created_next_releases: int | None
    active_created_prev_releases: int | None
    active_created_this_release: int | None
    active_total: int | None
    active_untouched_this_release: int | None
    active_updated_this_release: int | None
    created_this_release: int | None
    created_wo_predecessors: int | None
    created_wo_predecessors_v_1: int | None
    created_wo_predecessors_v_gt1: int | None
    created_w_predecessors: int | None
    created_w_predecessors_v_1: int | None
    created_w_predecessors_v_gt1: int | None
    dbid: int | None
    end_time: datetime.datetime | None
    ff_loaded_rows: int | None
    ff_taxid_nulls: int | None
    prev_release: int | None
    retired_next_releases: int | None
    retired_prev_releases: int | None
    retired_this_release: int | None
    retired_total: int | None
    start_time: datetime.datetime | None
    this_release: int


class RfamAnalyzedSequences(TypedDict):
    date: datetime.date
    rfam_version: str | None
    total_family_matches: int
    total_matches: int
    upi: str


class RfamClans(TypedDict):
    description: str
    family_count: int
    name: str
    rfam_clan_id: str


class RfamGoTerms(TypedDict):
    ontology_term_id: str
    rfam_go_term_id: int
    rfam_model_id: str


class RfamInitialAnnotations(TypedDict):
    rfam_initial_annotation_id: int
    rfam_model_id: str
    upi: str


class RfamModelHits(TypedDict):
    e_value: float
    model_completeness: float
    model_start: int
    model_stop: int
    overlap: str
    rfam_hit_id: int
    rfam_model_id: str
    score: float
    sequence_completeness: float
    sequence_start: int
    sequence_stop: int
    upi: str


class RfamModels(TypedDict):
    description: str | None
    domain: str | None
    full_count: int
    is_suppressed: bool
    length: int
    long_name: str
    rfam_clan_id: str | None
    rfam_model_id: str
    rfam_rna_type: str
    rna_type: str
    seed_count: int
    short_name: str
    so_rna_type: str | None


class Rna(TypedDict):
    crc64: str | None
    id: int | None
    len: int | None
    md5: str | None
    seq_long: str | None
    seq_short: str | None
    timestamp: datetime.datetime | None
    upi: str
    userstamp: str | None


class RncAcSrBackup(TypedDict):
    accession: str | None
    id: int | None
    region_id: int | None


class RncAccessionSequenceRegion(TypedDict):
    accession: str
    id: int
    region_id: int


class RncAccessions(TypedDict):
    accession: str
    allele: str | None
    anticodon: str | None
    chromosome: str | None
    classification: str | None
    common_name: str | None
    database: str | None
    db_xref: str | None
    description: str | None
    division: str | None
    experiment: str | None
    external_id: str | None
    feature_end: int | None
    feature_name: str | None
    feature_start: int | None
    function: str | None
    gene: str | None
    gene_synonym: str | None
    id: int | None
    inference: str | None
    is_composite: str | None
    keywords: str | None
    locus_tag: str | None
    map: str | None
    mol_type: str | None
    ncrna_class: str | None
    non_coding_id: str | None
    note: str | None
    old_locus_tag: str | None
    operon: str | None
    optional_id: str | None
    ordinal: int | None
    organelle: str | None
    parent_ac: str | None
    product: str | None
    project: str | None
    pseudogene: str | None
    rna_type: str | None
    seq_version: int | None
    species: str | None
    standard_name: str | None


class RncChemicalComponents(TypedDict):
    ccd_id: str | None
    description: str | None
    id: str
    modomics_short_name: str | None
    one_letter_code: str | None
    source: str | None


class RncCpatResults(TypedDict):
    coding_probability: float
    fickett_score: float
    hexamer_score: float
    is_protein_coding: bool
    urs_taxid: str


class RncDatabase(TypedDict):
    alive: str
    avg_length: int | None
    current_release: int | None
    descr: str
    display_name: str | None
    for_release: str | None
    full_descr: str | None
    id: int
    max_length: int | None
    min_length: int | None
    num_organisms: int | None
    num_sequences: int | None
    project_id: str | None
    timestamp: datetime.datetime
    userstamp: str


class RncDatabaseJsonStats(TypedDict):
    database: str
    length_counts: str | None
    taxonomic_lineage: str | None


class RncDatabaseReferences(TypedDict):
    dbid: int
    id: int
    reference_id: int


class RncFeedbackOverlap(TypedDict):
    assembly_id: str
    id: int
    no_overlaps_with: Any
    overlapping_upis: Any | None
    overlaps_with: Any
    should_ignore: bool | None
    upi_taxid: str


class RncFeedbackTargetAssemblies(TypedDict):
    assembly_id: str | None
    chromosome: str | None
    database: str | None
    dbid: int | None


class RncGeneStatus(TypedDict):
    assembly_id: str
    id: int
    region_id: int
    status: str
    urs_taxid: str


class RncImportTracker(TypedDict):
    db_id: int
    db_name: str
    file_md5: str | None
    id: int
    last_import_date: datetime.datetime | None


class RncInteractions(TypedDict):
    id: int
    intact_id: str
    interacting_id: str
    names: str
    taxid: int
    urs_taxid: str


class RncLocus(TypedDict):
    assembly_id: str
    chromosome: str
    id: int
    locus_name: str
    locus_start: int
    locus_stop: int
    member_count: int
    public_locus_name: str
    strand: str


class RncLocusMembers(TypedDict):
    id: int
    locus_id: int
    membership_status: str
    region_id: int
    urs_taxid: str


class RncModifications(TypedDict):
    accession: str
    author_assigned_position: int
    id: int
    modification_id: str
    position: int
    upi: str


class RncReferenceMap(TypedDict):
    accession: str
    id: int
    reference_id: int


class RncReferences(TypedDict):
    authors: str | None
    doi: str | None
    epmcid: str | None
    epmc_updated: int | None
    id: int
    location: str | None
    md5: str
    pmcid: str | None
    pmid: str | None
    title: str | None


class RncRelatedSequences(TypedDict):
    id: int
    methods: Any | None
    old_relationship_type: str | None
    relationship_type: str
    source_accession: str
    source_urs_taxid: str
    target_accession: str
    target_urs_taxid: str | None


class RncRelease(TypedDict):
    dbid: int
    descr: str | None
    force_load: str | None
    id: int
    release_date: datetime.datetime
    release_type: str
    status: str
    timestamp: datetime.datetime
    userstamp: str


class RncRnaPrecomputed(TypedDict):
    assigned_so_rna_type: str | None
    databases: str | None
    description: str | None
    has_coordinates: bool | None
    id: str
    is_active: bool | None
    is_locus_representative: bool | None
    last_release: int | None
    rna_type: str | None
    short_description: str | None
    so_rna_type: str | None
    taxid: int | None
    update_date: datetime.date | None
    upi: str


class RncSecondaryStructure(TypedDict):
    id: int | None
    md5: str | None
    rnc_accession_id: str | None
    secondary_structure: str | None


class RncSecondaryStructureLayout(TypedDict):
    assigned_should_show: bool | None
    basepair_count: int
    id: int
    inferred_should_show: bool
    model_coverage: float | None
    model_id: int
    model_start: int | None
    model_stop: int | None
    overlap_count: int
    secondary_structure: str
    sequence_coverage: float | None
    sequence_start: int | None
    sequence_stop: int | None
    stk: str | None
    urs: str


class RncSecondaryStructureLayoutModels(TypedDict):
    cellular_location: str | None
    id: int
    model_basepair_count: int
    model_length: int
    model_name: str
    model_source: str
    rna_type: str
    so_term_id: str
    taxid: int


class RncSequenceExons(TypedDict):
    exon_start: int
    exon_stop: int
    id: int
    region_id: int | None


class RncSequenceFeatures(TypedDict):
    accession: str | None
    feature_name: str
    metadata: str | None
    rnc_sequence_features_id: int
    start: int
    stop: int
    taxid: int
    upi: str


class RncSequenceRegions(TypedDict):
    assembly_id: str | None
    chromosome: str
    exon_count: int
    id: int
    identity: float | None
    providing_databases: Any
    region_name: str
    region_start: int
    region_stop: int
    strand: int
    urs_taxid: str
    was_mapped: bool


class RncTaxonomy(TypedDict):
    aliases: Any | None
    common_name: str | None
    id: int
    is_deleted: bool
    lineage: str
    name: str
    replaced_by: int | None


class UnindexedForeignKeys(TypedDict):
    existing_fk_on_referencing_tbl: Any | None
    referenced_column: str | None
    referenced_tbl: str | None
    referenced_tbl_size: str | None
    referencing_column: str | None
    referencing_tbl: str | None
    referencing_tbl_size: str | None
    suggestion: str | None


class ValidateLayoutCounts(TypedDict):
    changed: int
    inserted: int
    moved: int
    name: str
    not_drawn: int | None
    overlap_count: int | None
    rna_length: int | None
    rotated: int
    total: int
    unchanged: int


class ValidateLayoutHits(TypedDict):
    model_name: str | None
    model_rna_type: str | None
    model_so_rna_type: str | None
    model_source: str | None
    model_taxid: int | None
    sequence_rna_type: str | None
    sequence_taxid: int | None
    urs: str | None


class Xref(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefCount(TypedDict):
    upi: str | None
    xref_count: int | None


class XrefNotUnique(TypedDict):
    ac: str
    dbid: int
    release_id: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None


class XrefP10Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP10NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP11Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP11DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP11NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP11NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP12Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP12DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP12NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP12NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP13Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP13NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP14Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP14DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP14NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP14NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP15Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP15DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP15NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP15NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP16Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP16DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP16NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP16NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP17Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP17DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP17NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP17NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP18Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP18DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP18NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP18NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP19Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP19NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP1Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP1DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP1NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP1NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP20Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP20DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP20NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP20NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP21Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP21NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP22Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP22NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP23Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP23DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP23NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP23NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP24Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP24DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP24NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP24NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP25Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP25DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP25NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP25NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP26Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP26DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP26NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP26NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP27Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP27NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP28Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP28NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP29Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP29NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP2Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP2DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP2NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP2NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP30Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP30DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP30NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP30NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP31Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP31DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP31NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP31NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP32Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP32NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP33Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP33DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP33NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP33NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP34Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP34DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP34NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP34NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP35Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP35DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP35NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP35NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP36Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP36DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP36NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP36NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP37Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP37DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP37NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP37NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP38Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP38DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP38NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP38NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP39Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP39DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP39NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP39NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP3Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP3DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP3NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP3NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP40Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP40DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP40NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP40NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP41Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP41DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP41NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP41NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP42Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP42DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP42NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP42NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP43Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP43DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP43NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP43NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP44Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP44DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP44NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP44NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP45Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP45DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP45NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP45NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP46Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP46DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP46NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP46NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP47Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP47DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP47NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP47NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP48Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP48DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP48NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP48NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP49Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP49DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP49NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP49NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP4Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP4DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP4NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP4NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP50Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP50DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP50NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP50NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP51Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP51DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP51NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP51NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP52Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP52DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP52NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP52NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP53Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP53DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP53NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP53NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP5Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP5NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP6Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP6DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP6NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP6NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP7Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP7DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP7NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP7NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP8Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP8DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP8NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP8NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP9Deleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP9DeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP9NotDeleted(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int


class XrefP9NotDeletedOld(TypedDict):
    ac: str
    created: int
    dbid: int
    deleted: str
    id: int | None
    last: int
    taxid: int | None
    timestamp: datetime.datetime
    upi: str
    userstamp: str
    version: int | None
    version_i: int
